### ISSUE TITLE
과제 - 영화 예매 시스템 기능 추가

### ISSUE THREAD

**Issue by BinskLee** [BinskLee/Step-by-step-oop-study#9]
## 📋 사전 정보
> 다음은 과제는 스터디 교재 '오브젝트'의 저자이신 조영호님의 [Github 저장소](https://github.com/eternity-oop/object)에 업로드된 chapter02 디렉토리 밑에 있는 소스들 중 스텝2에 해당하는 코드를 기준으로 진행합니다.

위의 사항을 참고하여 아래의 요구사항을 만족시키는 코드를 작성해주세요!  제출은 모든 과제 소스들을 담은 디렉토리를 `code` 브랜치에 개인 PR로 날리는 형태로 하겠습니다.
### 예매 정보 확인 기능
```text
예매 UUID: 123e4567-e89b-42d3-a456-556642440000
제목: 오펜하이머
상영 유형: 2D
상영 시간: 180분
상영 날짜: 2023-08-25
상영 시각: 16:30
예매한 시간: 2023-08-23 09:30:27
예매 매수: 성인 2명, 청소년 1명, 어린이 1명
지불액: 49,000원
영화관: 성신여대점
상영관: 11층 09관
```
*예시: 유저가 자신의 예매를 확인*

### 예매 취소 기능
유저의 의사에 따라 특정 예매 항목에 대해서 예매를 취소할 수 있어야 함. 이 때, <ins>유저에게 환불되는 금액은 정가의 90%</ins>다. **단, 환불은 상영 날짜 당일 1시간 전까지만 가능**

## 🤨 기타 변경사항
기존의 코드베이스를 각자의 생각을 갖고 기능적 요구사항을 만족시키게끔 변경. 이에 따른 구체적인 제약사항은 없음.

**Comment by rkdtmddnjs97** [comment]
요구사항
1.  예매정보 확인 기능
    -  예매 uuid
    -  제목
    - 상영 유형
    - 상영 시간
    - 상영 날짜
    - 상영 시각
    -  예매한 시간
    -  예매 매수
    -  지불액
    -  영화관 
    - 상영관
2. 예매 정보 취소(환불) 기능 
   -  환불 조건 : 상영 날짜 당일 1시간 전까지 가능
   -  환불 액: 정가의 90퍼
   -  그 외 환불이 아닌 취소


과제에 대한 요구사항이 제가 이해한 것이 맞나요? 그렇다면 질문이있습니다  사용자가 예매 uuid를 확인해야 하는 이유가 궁금합니다

**Comment by BinskLee** [comment]
요구사항은 이해한게 맞고 uuid는 예매에 대한 일련번호를 제공해서 예매에 대한 식별을 진행하기 위해서 넣어둔건데... 근데 생각해보니 굳이 사용자에게 보여줄 필요가 없을 것 같긴합니다.
